vich_uploader:
    db_driver: orm

    mappings:
        default_photos:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'
            directory_namer: App\Service\Extra\EntityDirectoryNamerService
            namer: Vich\UploaderBundle\Naming\HashNamer
