
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> symfony/mercure-bundle ###
  mercure:
    ports:
      # Порт доступен только с localhost — Nginx проксирует снаружи.
      # Локально: http://localhost:9090/.well-known/mercure
      - "127.0.0.1:9090:80"
    environment:
      # В dev разрешаем все origins — не надо менять при смене порта фронтенда
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins *
        anonymous_is_allowed false
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
###< symfony/mercure-bundle ###
